# This workflow will run tests on PRs

name: Run PyTest On PRs

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Install dependencies and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: "3.6"
      - name: Run tests
        run: make REQUIRE_PIP=false install-test setup coverage twine-check
