# This workflow will run tests on PRs

name: Run PyTest On PRs

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Install dependencies and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.3.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
      - name: Run tests
        run: pytest tests # --doctest-modules --cov=ppsetuptools
